name: Throughput test

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  TOLERANCE_PERCENTAGE: 5.0 # 5% tolerance for wall time increase
  # If true, data required to bootstrap MongoDB and the Kafka producer 
  # are deleted before we start processing to save storage space. 
  # This is useful for CI environments where storage is limited.
  LOW_STORAGE: true

jobs:
  test:
    name: Run throughput test
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          clean: false
          lfs: "true"
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build & Cache Docker images
        uses: docker/bake-action@v2
        with:
          workdir: ./tests/throughput
          load: true
          set: |
            *.cache-to=type=gha,mode=max
            *.cache-from=type=gha
        env:
          PWD: ${{ github.workspace }}
          BUILDX_BAKE_ENTITLEMENTS_FS: 0
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
      - name: Download NED catalog from Google Drive
        run: |
          mkdir -p ./data/alerts
          uvx gdown https://drive.google.com/uc?id=1BG46oLMbONXhIqiPrepSnhKim1xfiVbB -O ./data/alerts/kowalski.NED.json.gz
      - name: Download auxiliary ZTF alerts from Google Drive
        run: |
          mkdir -p ./data/alerts
          uvx gdown https://drive.google.com/uc?id=126uLk7xah2EpJR741ziPO-cxQ43nZUoL -O ./data/alerts/boom_throughput.ZTF_alerts_aux.dump.gz
      - name: Run test
        run: |
          uv run tests/throughput/run.py
      - name: Upload logs (including wall time) as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: throughput-logs
          path: logs/boom-*
      - name: Download baseline benchmark (PR only)
        if: github.event_name == 'pull_request'
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: test-throughput.yaml
          branch: main
          name: throughput-logs
          path: ./baseline
          if_no_artifact_found: warn
        continue-on-error: true
      - name: Compare with baseline (PR only)
        id: compare-with-baseline
        # The artifact (is it exists) should have a file called wall_time.txt
        # so if the file doesn't exist we skip this action, otherwise we
        # compare the wall time
        if: github.event_name == 'pull_request'
        run: |
          current=$(cat logs/boom-*/wall_time.txt)
          echo "Current wall time: $current seconds"
          if [ -f ./baseline/boom-*/wall_time.txt ]; then
            baseline=$(cat ./baseline/boom-*/wall_time.txt)
            echo "Baseline wall time: $baseline seconds"
            percentage_diff=$(echo "scale=2; (($current - $baseline) / $baseline) * 100" | bc)
          else
            echo "No baseline wall time found. Skipping comparison."
            percentage_diff=0
          fi

          echo "Percentage difference: $percentage_diff%"

          echo "percentage_diff=$percentage_diff" >> $GITHUB_OUTPUT
          echo "baseline=$baseline" >> $GITHUB_OUTPUT
          echo "current=$current" >> $GITHUB_OUTPUT
      - name: Post comment on PR (if applicable)
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Throughput results (`${{ github.sha }}`):
            | New wall time | Baseline wall time | Difference |
            | -------------- | ------------------ | ---------- |
            | ${{ steps.compare-with-baseline.outputs.current }} | ${{ steps.compare-with-baseline.outputs.baseline }} | ${{ steps.compare-with-baseline.outputs.percentage_diff }}% |
          edit-mode: replace
      - name: Fail if wall time increased too much (PR only)
        if: github.event_name == 'pull_request'
        run: |
          percentage_diff=${{ steps.compare-with-baseline.outputs.percentage_diff }}
          if (( $(echo "$percentage_diff > $TOLERANCE_PERCENTAGE" | bc -l) )); then
            echo "Wall time increased by $percentage_diff%, which is more than the allowed $TOLERANCE_PERCENTAGE%."
            exit 1
          fi
